# coding: utf-8
from sqlalchemy import BigInteger, Column, Float, ForeignKey, Integer, String, Table, Text, text
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class Book(Base):
    __tablename__ = 'books'

    id = Column(Integer, primary_key=True, server_default=text("nextval('books_id_seq'::regclass)"))
    name = Column(String(125), nullable=False)

    users = relationship('User', secondary='book_users')


t_ga_campaigns_bulk = Table(
    'ga_campaigns_bulk', metadata,
    Column('campanha', Text),
    Column('ordernumber', Text)
)


t_ga_channels_bulk = Table(
    'ga_channels_bulk', metadata,
    Column('canal', Text),
    Column('ordernumber', Text)
)


t_ga_orders_info = Table(
    'ga_orders_info', metadata,
    Column('ordernumber', Text),
    Column('Source', Text),
    Column('Canal', Text),
    Column('Campanha', Text)
)


t_ga_source_bulk = Table(
    'ga_source_bulk', metadata,
    Column('source', Text),
    Column('ordernumber', Text)
)


t_last_update_date = Table(
    'last_update_date', metadata,
    Column('last_update_date', Text)
)


t_manual_enderecos = Table(
    'manual_enderecos', metadata,
    Column('endereço', Text),
    Column('bairro', Text),
    Column('cidade', Text),
    Column('estado', Text),
    Column('cep', Integer),
    Column('latitude', Text),
    Column('longitude', Text)
)


t_manual_productids = Table(
    'manual_productids', metadata,
    Column('id', BigInteger),
    Column('categoria', Text),
    Column('capsula', Text),
    Column('productid', Text),
    Column('tipo', Text),
    Column('multiplicador_dose', Float(53)),
    Column('multiplicador_capsula', Float(53)),
    Column('multiplicador_caixa', Float(53)),
    Column('child_productid', Text),
    Column('sku_ga', Text),
    Column('produto_ga', Text)
)


t_manual_productids_temp = Table(
    'manual_productids_temp', metadata,
    Column('categoria', Text),
    Column('capsula', Text),
    Column('productid', Text),
    Column('tipo', Text),
    Column('multiplicador_dose', Text),
    Column('multiplicador_capsula', Text),
    Column('multiplicador_caixa', Text),
    Column('child_productid', Text),
    Column('sku_ga', Text),
    Column('produto_ga', Text)
)


t_manual_rule_ids = Table(
    'manual_rule_ids', metadata,
    Column('applied_rule_ids', Text),
    Column('tipo', Text)
)


t_manual_rule_ids_concat = Table(
    'manual_rule_ids_concat', metadata,
    Column('tipo', Text),
    Column('rules', Text),
    Column('query', Text)
)


t_manual_rule_ids_query = Table(
    'manual_rule_ids_query', metadata,
    Column('tipo', Text),
    Column('query_1', Text),
    Column('query_2', Text),
    Column('query_3', Text),
    Column('query_4', Text)
)


t_mg_blisspoints_report_bulk_temp = Table(
    'mg_blisspoints_report_bulk_temp', metadata,
    Column('customerid', Text),
    Column('balance', Text),
    Column('points', Text),
    Column('reason', Text),
    Column('createdat', Text),
    Column('expiredat', Text),
    Column('comment', Text),
    Column('Update Date', Text)
)


t_mg_email_optinout_bulk_1 = Table(
    'mg_email_optinout_bulk_1', metadata,
    Column('customerid', Text),
    Column('firstname', Text),
    Column('lastname', Text),
    Column('customeremail', Text),
    Column('status', Text),
    Column('optindate', Text),
    Column('optoutdate', Text),
    Column('updatedate', Text)
)


t_mg_email_optinout_bulk_2 = Table(
    'mg_email_optinout_bulk_2', metadata,
    Column('customerid', Text),
    Column('customer_type', Text),
    Column('firstname', Text),
    Column('lastname', Text),
    Column('email', Text),
    Column('status', Text),
    Column('segments', Text),
    Column('subscriptiontype', Text),
    Column('creationdate', Text),
    Column('updatedate', Text)
)


t_mg_new_product_ids = Table(
    'mg_new_product_ids', metadata,
    Column('product_id', Text),
    Column('sku', Text)
)


t_mg_orders_dbm_bulk = Table(
    'mg_orders_dbm_bulk', metadata,
    Column('customer_id', Text),
    Column('customer_email', Text),
    Column('customer_fiscalcode', Text),
    Column('increment_id', Text),
    Column('created_at', Text),
    Column('status', Text),
    Column('item_id', Text),
    Column('product_id', Text),
    Column('sku', Text),
    Column('qty_ordered', Text),
    Column('orginal_price', Text),
    Column('subtotal', Text),
    Column('base_discount_amount', Text),
    Column('base_grand_total', Text),
    Column('base_total_paid', Text),
    Column('method', Text),
    Column('base_shipping_amount', Text),
    Column('deliveryaddress', Text),
    Column('city', Text),
    Column('region', Text),
    Column('postcode', Text),
    Column('applied_rule_ids', Text),
    Column('updated_at', Text),
    Column('status_sequence', BigInteger)
)


t_mg_orders_dbm_bulk_temp = Table(
    'mg_orders_dbm_bulk_temp', metadata,
    Column('customer_id', Text),
    Column('customer_email', Text),
    Column('customer_fiscalcode', Text),
    Column('increment_id', Text),
    Column('created_at', Text),
    Column('status', Text),
    Column('item_id', Text),
    Column('product_id', Text),
    Column('sku', Text),
    Column('qty_ordered', Text),
    Column('orginal_price', Text),
    Column('subtotal', Text),
    Column('base_discount_amount', Text),
    Column('base_grand_total', Text),
    Column('base_total_paid', Text),
    Column('method', Text),
    Column('base_shipping_amount', Text),
    Column('deliveryaddress', Text),
    Column('city', Text),
    Column('region', Text),
    Column('postcode', Text),
    Column('applied_rule_ids', Text),
    Column('updated_at', Text)
)


t_mg_orders_dbm_bulk_temp_2 = Table(
    'mg_orders_dbm_bulk_temp_2', metadata,
    Column('customer_id', Text),
    Column('customer_email', Text),
    Column('customer_fiscalcode', Text),
    Column('increment_id', Text),
    Column('created_at', Text),
    Column('status', Text),
    Column('item_id', Text),
    Column('product_id', Text),
    Column('sku', Text),
    Column('qty_ordered', Text),
    Column('orginal_price', Text),
    Column('subtotal', Text),
    Column('base_discount_amount', Text),
    Column('base_grand_total', Text),
    Column('base_total_paid', Text),
    Column('method', Text),
    Column('base_shipping_amount', Text),
    Column('deliveryaddress', Text),
    Column('city', Text),
    Column('region', Text),
    Column('postcode', Text),
    Column('applied_rule_ids', Text),
    Column('updated_at', Text)
)


t_mg_promotionid_report_bulk = Table(
    'mg_promotionid_report_bulk', metadata,
    Column('ruleid', Text),
    Column('customergroups', Text),
    Column('name', Text),
    Column('status', Text),
    Column('fromdate', Text),
    Column('todate', Text)
)


t_mg_rule_names = Table(
    'mg_rule_names', metadata,
    Column('applied_rule_ids', Text),
    Column('applied_rule_names', Text)
)


t_mg_subscriptions_weekly_report_bulk = Table(
    'mg_subscriptions_weekly_report_bulk', metadata,
    Column('status', Text),
    Column('subscriber_sexo', Text),
    Column('email', Text)
)


t_mg_subscriptions_weekly_report_bulk_temp = Table(
    'mg_subscriptions_weekly_report_bulk_temp', metadata,
    Column('referenceid', Text),
    Column('customerid', Text),
    Column('status', Text),
    Column('startedat', Text),
    Column('lastbilled', Text),
    Column('subscriber', Text),
    Column('address', Text),
    Column('cep', Text),
    Column('billing_city', Text),
    Column('billing_state', Text),
    Column('billing_country', Text),
    Column('email', Text),
    Column('cpf', Text),
    Column('billing_telephone', Text),
    Column('mobile', Text),
    Column('dob', Text),
    Column('updated_at', Text)
)


t_orders_address_orders_3 = Table(
    'orders_address_orders_3', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('ordernumber', Text),
    Column('Assinatura', Text),
    Column('item_id', Integer),
    Column('orderdate', Float(53)),
    Column('Last_Update_Date', Text),
    Column('Days_Since_Last_Update', Float(53)),
    Column('Ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('order_status', Text),
    Column('productid', Text),
    Column('sku', Text),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('Cidade', Text),
    Column('Estado', Text),
    Column('cep', Float(53)),
    Column('applied_rule_ids', Text),
    Column('applied_rule_names', Text),
    Column('OptinOut', Text),
    Column('Gênero', Text),
    Column('Source', Text),
    Column('Canal', Text),
    Column('Campanha', Text)
)


t_orders_calendar_1 = Table(
    'orders_calendar_1', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_0 = Table(
    'orders_calendar_1_letter_0', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_1 = Table(
    'orders_calendar_1_letter_1', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_2 = Table(
    'orders_calendar_1_letter_2', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_3 = Table(
    'orders_calendar_1_letter_3', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_4 = Table(
    'orders_calendar_1_letter_4', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_5 = Table(
    'orders_calendar_1_letter_5', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_6 = Table(
    'orders_calendar_1_letter_6', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_7 = Table(
    'orders_calendar_1_letter_7', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_8 = Table(
    'orders_calendar_1_letter_8', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_9 = Table(
    'orders_calendar_1_letter_9', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter__ = Table(
    'orders_calendar_1_letter__', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_a = Table(
    'orders_calendar_1_letter_a', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_b = Table(
    'orders_calendar_1_letter_b', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_c = Table(
    'orders_calendar_1_letter_c', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_d = Table(
    'orders_calendar_1_letter_d', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_e = Table(
    'orders_calendar_1_letter_e', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_f = Table(
    'orders_calendar_1_letter_f', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_g = Table(
    'orders_calendar_1_letter_g', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_h = Table(
    'orders_calendar_1_letter_h', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_i = Table(
    'orders_calendar_1_letter_i', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_j = Table(
    'orders_calendar_1_letter_j', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_k = Table(
    'orders_calendar_1_letter_k', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_l = Table(
    'orders_calendar_1_letter_l', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_m = Table(
    'orders_calendar_1_letter_m', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_n = Table(
    'orders_calendar_1_letter_n', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_o = Table(
    'orders_calendar_1_letter_o', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_p = Table(
    'orders_calendar_1_letter_p', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_q = Table(
    'orders_calendar_1_letter_q', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_r = Table(
    'orders_calendar_1_letter_r', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_s = Table(
    'orders_calendar_1_letter_s', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_t = Table(
    'orders_calendar_1_letter_t', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_u = Table(
    'orders_calendar_1_letter_u', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_v = Table(
    'orders_calendar_1_letter_v', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_w = Table(
    'orders_calendar_1_letter_w', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_x = Table(
    'orders_calendar_1_letter_x', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_y = Table(
    'orders_calendar_1_letter_y', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_letter_z = Table(
    'orders_calendar_1_letter_z', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53))
)


t_orders_calendar_1_temp = Table(
    'orders_calendar_1_temp', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_0 = Table(
    'orders_calendar_1_temp_letter_0', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_1 = Table(
    'orders_calendar_1_temp_letter_1', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_2 = Table(
    'orders_calendar_1_temp_letter_2', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_3 = Table(
    'orders_calendar_1_temp_letter_3', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_4 = Table(
    'orders_calendar_1_temp_letter_4', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_5 = Table(
    'orders_calendar_1_temp_letter_5', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_6 = Table(
    'orders_calendar_1_temp_letter_6', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_7 = Table(
    'orders_calendar_1_temp_letter_7', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_8 = Table(
    'orders_calendar_1_temp_letter_8', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_9 = Table(
    'orders_calendar_1_temp_letter_9', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter__ = Table(
    'orders_calendar_1_temp_letter__', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_a = Table(
    'orders_calendar_1_temp_letter_a', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_b = Table(
    'orders_calendar_1_temp_letter_b', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_c = Table(
    'orders_calendar_1_temp_letter_c', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_d = Table(
    'orders_calendar_1_temp_letter_d', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_e = Table(
    'orders_calendar_1_temp_letter_e', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_f = Table(
    'orders_calendar_1_temp_letter_f', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_g = Table(
    'orders_calendar_1_temp_letter_g', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_h = Table(
    'orders_calendar_1_temp_letter_h', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_i = Table(
    'orders_calendar_1_temp_letter_i', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_j = Table(
    'orders_calendar_1_temp_letter_j', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_k = Table(
    'orders_calendar_1_temp_letter_k', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_l = Table(
    'orders_calendar_1_temp_letter_l', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_m = Table(
    'orders_calendar_1_temp_letter_m', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_n = Table(
    'orders_calendar_1_temp_letter_n', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_o = Table(
    'orders_calendar_1_temp_letter_o', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_p = Table(
    'orders_calendar_1_temp_letter_p', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_q = Table(
    'orders_calendar_1_temp_letter_q', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_r = Table(
    'orders_calendar_1_temp_letter_r', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_s = Table(
    'orders_calendar_1_temp_letter_s', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_t = Table(
    'orders_calendar_1_temp_letter_t', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_u = Table(
    'orders_calendar_1_temp_letter_u', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_v = Table(
    'orders_calendar_1_temp_letter_v', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_w = Table(
    'orders_calendar_1_temp_letter_w', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_x = Table(
    'orders_calendar_1_temp_letter_x', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_y = Table(
    'orders_calendar_1_temp_letter_y', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_calendar_1_temp_letter_z = Table(
    'orders_calendar_1_temp_letter_z', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('orderdate', Float(53)),
    Column('created_at', Text),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53))
)


t_orders_client_2 = Table(
    'orders_client_2', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('item_id', Integer),
    Column('ordernumber', Text),
    Column('order_status', Text),
    Column('orderdate', Float(53)),
    Column('assinatura', Text),
    Column('applied_rule_ids', Text),
    Column('last_update_date', Text),
    Column('days_since_last_update', Float(53)),
    Column('ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('sku', Text),
    Column('productid', Integer),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('cep', Float(53)),
    Column('OptinOut', Text),
    Column('Gênero', Text)
)


t_orders_complete_temp = Table(
    'orders_complete_temp', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('ordernumber', Text),
    Column('Assinatura', Text),
    Column('item_id', Integer),
    Column('orderdate', Float(53)),
    Column('Last_Update_Date', Text),
    Column('Days_Since_Last_Update', Float(53)),
    Column('Ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('order_status', Text),
    Column('productid', Text),
    Column('sku', Text),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal_diluido', Float(53)),
    Column('preco_desconto_diluido', Float(53)),
    Column('preco_frete_diluido', Float(53)),
    Column('preco_final', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('Cidade', Text),
    Column('Estado', Text),
    Column('cep', Float(53)),
    Column('applied_rule_ids', Text),
    Column('applied_rule_names', Text),
    Column('categoria', Text),
    Column('capsula', Text),
    Column('tipo', Text),
    Column('Frete Grátis', Integer),
    Column('Desconto', Integer),
    Column('Bônus_Blisspoints', Integer),
    Column('Evento', Integer),
    Column('Relacionamento', Integer),
    Column('Promo Assinatura', Integer),
    Column('Ignorar', Integer),
    Column('Quantidade Dose', Float(53)),
    Column('Quantidade Cápsula', Float(53)),
    Column('Quantidade Caixa', Float(53)),
    Column('child_productid', Text),
    Column('Produto', Text),
    Column('OptinOut', Text),
    Column('Gênero', Text),
    Column('Source', Text),
    Column('Canal', Text),
    Column('Campanha', Text),
    Column('POSSUI_DSJ', Integer),
    Column('POSSUI_CAIXA_NORMAL', Integer),
    Column('POSSUI_ACESSÓRIO', Integer),
    Column('POSSUI_MÁQUINA', Integer),
    Column('POSSUI_COMBO', Integer)
)


t_orders_info = Table(
    'orders_info', metadata,
    Column('ordernumber', Text),
    Column('order_itens', BigInteger),
    Column('productid', Text),
    Column('kit_itens', BigInteger)
)


t_orders_info_types = Table(
    'orders_info_types', metadata,
    Column('ordernumber', Text),
    Column('tipo_concat', Text)
)


t_orders_product_4 = Table(
    'orders_product_4', metadata,
    Column('email', Text),
    Column('customerid', Text),
    Column('ordernumber', Text),
    Column('Assinatura', Text),
    Column('item_id', Integer),
    Column('orderdate', Float(53)),
    Column('Last_Update_Date', Text),
    Column('Days_Since_Last_Update', Float(53)),
    Column('Ano', Text),
    Column('Mês_Número', Text),
    Column('Dia', Text),
    Column('Hora', Float(53)),
    Column('Data', Text),
    Column('Data_Date', Text),
    Column('Semana', Float(53)),
    Column('Dia Semana Número', Float(53)),
    Column('Dia Semana', Text),
    Column('Quarter', Integer),
    Column('order_status', Text),
    Column('productid', Text),
    Column('sku', Text),
    Column('quantidade', Integer),
    Column('preco_original', Float(53)),
    Column('preco_subtotal', Float(53)),
    Column('preco_desconto', Float(53)),
    Column('preco_frete', Float(53)),
    Column('preco_total_pago', Float(53)),
    Column('Cidade', Text),
    Column('Estado', Text),
    Column('cep', Float(53)),
    Column('applied_rule_ids', Text),
    Column('applied_rule_names', Text),
    Column('categoria', Text),
    Column('capsula', Text),
    Column('tipo', Text),
    Column('Frete Grátis', Integer),
    Column('Desconto', Integer),
    Column('Bônus_Blisspoints', Integer),
    Column('Evento', Integer),
    Column('Relacionamento', Integer),
    Column('Promo Assinatura', Integer),
    Column('Ignorar', Integer),
    Column('Quantidade Dose', Float(53)),
    Column('Quantidade Cápsula', Float(53)),
    Column('Quantidade Caixa', Float(53)),
    Column('child_productid', Text),
    Column('Produto', Text),
    Column('OptinOut', Text),
    Column('Gênero', Text),
    Column('Source', Text),
    Column('Canal', Text),
    Column('Campanha', Text)
)


t_price_crawler_hist_temp = Table(
    'price_crawler_hist_temp', metadata,
    Column('product_name', Text),
    Column('data_extracao', Text),
    Column('loja', Text),
    Column('price_num', Text),
    Column('url', Text)
)


class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, server_default=text("nextval('users_id_seq'::regclass)"))
    name = Column(String(84), nullable=False)
    email = Column(String(84), nullable=False, unique=True)
    password = Column(String(255), nullable=False)


t_book_users = Table(
    'book_users', metadata,
    Column('user_id', ForeignKey('users.id'), nullable=False),
    Column('book_id', ForeignKey('books.id'), nullable=False)
)


class Profile(Base):
    __tablename__ = 'profiles'

    id = Column(Integer, primary_key=True, server_default=text("nextval('profiles_id_seq'::regclass)"))
    photo = Column(String(124), nullable=False)
    user_id = Column(ForeignKey('users.id'))

    user = relationship('User')
